<?php
/**
 * FreeITSM REST API v1 — calendar resource (the standalone team calendar).
 *
 * Mirrors the module's internal endpoints:
 *   - the list uses get_events.php's exact three-branch window-overlap logic
 *     (start inclusive, end exclusive);
 *   - create/update mirror save_event.php (title + start mandatory, end
 *     defaults to start, all_day 0/1) with friendlier validation: category /
 *     contract ids get a 422 instead of a raw FK error, and contract links
 *     honour nothing tenant-y because the calendar is install-wide.
 *
 * ⚠️ Datetime semantics — DIFFERENT from the rest of the API, deliberately:
 * calendar events are stored as NAIVE SERVER-LOCAL datetimes (the UI writes
 * what the browser sends, no timezone conversion; the ICS feed interprets
 * them in the server timezone). To stay pixel-identical with the UI, this
 * resource accepts and returns naive "YYYY-MM-DD HH:MM:SS" values with NO
 * timezone conversion, and REJECTS values carrying Z/offset designators so a
 * consumer can't accidentally mix models.
 *
 * 🛡️ Generated events: the asset-warranty sync owns every row with
 * source = 'asset_warranty' (it wipes and regenerates them wholesale). The
 * API exposes `source` on reads (the internal endpoints don't!) and refuses
 * updates/deletes on generated rows with a 409 — tighter than the UI, which
 * currently lets you edit one only for the change to evaporate on the next
 * sync. Consumers can never set `source` on create.
 */

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse a NAIVE local datetime ("YYYY-MM-DD HH:MM[:SS]", T separator OK,
 * date-only OK). 422s on timezone designators — this resource is naive-local
 * by design (see header).
 */
function apiParseNaiveDatetime($value, string $field): ?string {
    if ($value === null || $value === '') {
        return null;
    }
    $v = trim((string)$value);
    if (preg_match('/(Z|[+-]\d{2}:?\d{2})$/i', $v)) {
        apiError(422, 'invalid_field', "'{$field}' must be a naive local datetime (no Z/offset) — the calendar stores server-local times, matching the UI.");
    }
    $v = str_replace('T', ' ', $v);
    if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $v)) {
        $v .= ' 00:00:00';
    } elseif (preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/', $v)) {
        $v .= ':00';
    }
    $dt = DateTime::createFromFormat('Y-m-d H:i:s', $v);
    if (!$dt || $dt->format('Y-m-d H:i:s') !== $v) {
        apiError(422, 'invalid_field', "'{$field}' must be 'YYYY-MM-DD HH:MM:SS' (naive local time).");
    }
    return $v;
}

function apiCalendarEventSelect(): string {
    return "SELECT e.*, c.name AS category_name, c.color AS category_color,
                   a.full_name AS created_by_name
            FROM calendar_events e
            LEFT JOIN calendar_categories c ON c.id = e.category_id
            LEFT JOIN analysts a ON a.id = e.created_by";
}

function apiSerializeCalendarEvent(array $r): array {
    return [
        'id'          => (int)$r['id'],
        'title'       => $r['title'],
        'description' => $r['description'],
        'category'    => $r['category_id'] === null ? null : [
            'id'    => (int)$r['category_id'],
            'name'  => $r['category_name'],
            'color' => $r['category_color'],
        ],
        'start_at'    => $r['start_datetime'],   // naive server-local, by design
        'end_at'      => $r['end_datetime'],
        'all_day'     => (bool)$r['all_day'],
        'location'    => $r['location'],
        'contract_id' => $r['contract_id'] !== null ? (int)$r['contract_id'] : null,
        'source'      => $r['source'],           // null = manual; 'asset_warranty' = generated (read-only)
        'created_by'  => ((int)$r['created_by'] > 0)
            ? ['id' => (int)$r['created_by'], 'name' => $r['created_by_name']]
            : null, // generated events use the 0 sentinel
        'created_at'  => $r['created_at'],
        'updated_at'  => $r['updated_at'],
    ];
}

function apiLoadCalendarEvent(PDO $conn, int $eventId): array {
    $stmt = $conn->prepare(apiCalendarEventSelect() . " WHERE e.id = ?");
    $stmt->execute([$eventId]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    if (!$row) {
        apiError(404, 'not_found', 'Event not found.');
    }
    return $row;
}

/** Generated rows belong to their sync — the API never touches them. */
function apiCalendarGuardGenerated(array $event): void {
    if ($event['source'] !== null && $event['source'] !== '') {
        apiError(409, 'conflict', "This event is generated by the '{$event['source']}' sync and is read-only — it would be recreated on the next sync anyway.");
    }
}

// ---------------------------------------------------------------------------
// GET /calendar/events
// ---------------------------------------------------------------------------
function apiCalendarEventsList(PDO $conn, array $apiKey, array $params, array $body): void {
    $from = isset($_GET['from']) ? apiParseNaiveDatetime($_GET['from'], 'from') : null;
    $to   = isset($_GET['to'])   ? apiParseNaiveDatetime($_GET['to'], 'to')     : null;
    $all        = (($_GET['all'] ?? '') === 'true');
    $contractId = isset($_GET['contract_id']) && $_GET['contract_id'] !== '' ? (int)$_GET['contract_id'] : null;

    // Same rule as get_events.php: a window is required unless you're pulling
    // a contract's events or explicitly asked for everything.
    if (($from === null || $to === null) && !$all && $contractId === null) {
        apiError(400, 'invalid_parameter', "Provide a 'from' + 'to' window, or contract_id, or all=true.");
    }

    $where = ['1=1'];
    $args  = [];

    if ($from !== null && $to !== null) {
        // The UI's exact three-branch overlap: starts in / ends in / spans.
        $where[] = "( (e.start_datetime >= ? AND e.start_datetime < ?)
                   OR (e.end_datetime   >  ? AND e.end_datetime  <= ?)
                   OR (e.start_datetime <  ? AND e.end_datetime  >  ?) )";
        array_push($args, $from, $to, $from, $to, $from, $to);
    }
    if ($contractId !== null) {
        $where[] = 'e.contract_id = ?';
        $args[]  = $contractId;
    }
    if (isset($_GET['category_id']) && $_GET['category_id'] !== '') {
        $where[] = 'e.category_id = ?';
        $args[]  = (int)$_GET['category_id'];
    }
    if (isset($_GET['categories']) && trim($_GET['categories']) !== '') {
        $ids = array_values(array_filter(array_map('intval', explode(',', $_GET['categories'])), fn($i) => $i > 0));
        if ($ids) {
            $where[] = 'e.category_id IN (' . implode(',', array_fill(0, count($ids), '?')) . ')';
            $args = array_merge($args, $ids);
        }
    }
    $source = trim($_GET['source'] ?? '');
    if ($source === 'manual') {
        $where[] = 'e.source IS NULL';
    } elseif ($source !== '') {
        $where[] = 'e.source = ?';
        $args[]  = $source;
    }
    if (isset($_GET['q']) && trim($_GET['q']) !== '') {
        $where[] = '(e.title LIKE ? OR e.location LIKE ?)';
        $like = '%' . trim($_GET['q']) . '%';
        array_push($args, $like, $like);
    }

    [$page, $perPage, $offset] = apiPagination();
    $whereSql = implode(' AND ', $where);

    $countStmt = $conn->prepare("SELECT COUNT(*) FROM calendar_events e WHERE $whereSql");
    $countStmt->execute($args);
    $total = (int)$countStmt->fetchColumn();

    $stmt = $conn->prepare(apiCalendarEventSelect() . " WHERE $whereSql ORDER BY e.start_datetime ASC, e.id ASC LIMIT $perPage OFFSET $offset");
    $stmt->execute($args);
    apiRespond(array_map('apiSerializeCalendarEvent', $stmt->fetchAll(PDO::FETCH_ASSOC)), 200, [
        'page'        => $page,
        'per_page'    => $perPage,
        'total'       => $total,
        'total_pages' => (int)ceil($total / $perPage),
    ]);
}

function apiCalendarEventsGet(PDO $conn, array $apiKey, array $params, array $body): void {
    apiRespond(apiSerializeCalendarEvent(apiLoadCalendarEvent($conn, $params[0])));
}

// ---------------------------------------------------------------------------
// POST /calendar/events
// ---------------------------------------------------------------------------
function apiCalendarEventsCreate(PDO $conn, array $apiKey, array $params, array $body): void {
    $f = apiCalendarEventFields($conn, $body);
    if ($f['title'] === '') {
        apiError(422, 'missing_field', "'title' is required.");
    }
    if ($f['start'] === null) {
        apiError(422, 'missing_field', "'start_at' is required.");
    }

    // Consumers can never set source — new events are always manual.
    $ins = $conn->prepare(
        "INSERT INTO calendar_events (title, description, category_id, start_datetime,
            end_datetime, all_day, location, contract_id, created_by)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"
    );
    $ins->execute([
        $f['title'], $f['description'], $f['category_id'], $f['start'],
        $f['end'] ?? $f['start'], $f['all_day'], $f['location'], $f['contract_id'],
        (int)$apiKey['analyst_id'],
    ]);

    apiRespond(apiSerializeCalendarEvent(apiLoadCalendarEvent($conn, (int)$conn->lastInsertId())), 201);
}

/** Shared field collection/validation for create + patch. */
function apiCalendarEventFields(PDO $conn, array $body, array $current = []): array {
    $get = function (string $key, $default = null) use ($body, $current) {
        return array_key_exists($key, $body) ? $body[$key] : ($current[$key] ?? $default);
    };
    $f = [];
    $f['title']       = trim((string)$get('title', ''));
    $f['description'] = ($v = trim((string)($get('description') ?? ''))) !== '' ? $v : null;
    $f['location']    = ($v = trim((string)($get('location') ?? ''))) !== '' ? $v : null;
    $f['all_day']     = $get('all_day', 0) ? 1 : 0;

    $f['start'] = array_key_exists('start_at', $body)
        ? apiParseNaiveDatetime($body['start_at'], 'start_at')
        : ($current['start_datetime'] ?? null);
    $f['end'] = array_key_exists('end_at', $body)
        ? apiParseNaiveDatetime($body['end_at'], 'end_at')
        : ($current['end_datetime'] ?? null);
    if ($f['start'] !== null && $f['end'] !== null && $f['end'] < $f['start']) {
        apiError(422, 'invalid_field', "'end_at' cannot be before 'start_at'.");
    }

    // Friendly validation the UI leaves to raw FK errors.
    $f['category_id'] = null;
    $catRaw = $get('category_id');
    if ($catRaw !== null && $catRaw !== '') {
        $f['category_id'] = (int)$catRaw;
        $c = $conn->prepare("SELECT id FROM calendar_categories WHERE id = ?");
        $c->execute([$f['category_id']]);
        if (!$c->fetchColumn()) {
            apiError(422, 'invalid_field', "Unknown category id: {$f['category_id']}");
        }
    }
    $f['contract_id'] = null;
    $conRaw = $get('contract_id');
    if ($conRaw !== null && $conRaw !== '') {
        $f['contract_id'] = (int)$conRaw;
        try {
            $c = $conn->prepare("SELECT id FROM contracts WHERE id = ?");
            $c->execute([$f['contract_id']]);
            if (!$c->fetchColumn()) {
                apiError(422, 'invalid_field', "Unknown contract id: {$f['contract_id']}");
            }
        } catch (PDOException $e) {
            apiError(422, 'invalid_field', 'Contract links are not available on this install.');
        }
    }
    return $f;
}

// ---------------------------------------------------------------------------
// PATCH /calendar/events/{id}
// ---------------------------------------------------------------------------
function apiCalendarEventsUpdate(PDO $conn, array $apiKey, array $params, array $body): void {
    $current = apiLoadCalendarEvent($conn, $params[0]);
    apiCalendarGuardGenerated($current);
    if (!$body) {
        apiError(422, 'missing_field', 'No fields to update.');
    }
    $f = apiCalendarEventFields($conn, $body, $current);
    if ($f['title'] === '') {
        apiError(422, 'invalid_field', "'title' cannot be empty.");
    }
    if ($f['start'] === null) {
        apiError(422, 'invalid_field', "'start_at' cannot be cleared.");
    }
    if (!array_key_exists('all_day', $body)) {
        $f['all_day'] = (int)$current['all_day'];
    }

    // WHERE source IS NULL: belt-and-braces against a sync racing us.
    $upd = $conn->prepare(
        "UPDATE calendar_events SET title=?, description=?, category_id=?, start_datetime=?,
            end_datetime=?, all_day=?, location=?, contract_id=?, updated_at=UTC_TIMESTAMP()
         WHERE id=? AND source IS NULL"
    );
    $upd->execute([
        $f['title'], $f['description'], $f['category_id'], $f['start'],
        $f['end'] ?? $f['start'], $f['all_day'], $f['location'], $f['contract_id'],
        $params[0],
    ]);

    apiRespond(apiSerializeCalendarEvent(apiLoadCalendarEvent($conn, $params[0])));
}

// ---------------------------------------------------------------------------
// DELETE /calendar/events/{id}
// ---------------------------------------------------------------------------
function apiCalendarEventsDelete(PDO $conn, array $apiKey, array $params, array $body): void {
    $current = apiLoadCalendarEvent($conn, $params[0]);
    apiCalendarGuardGenerated($current);
    $conn->prepare("DELETE FROM calendar_events WHERE id = ? AND source IS NULL")->execute([$params[0]]);
    apiRespond(['id' => $params[0], 'deleted' => true]);
}

// ---------------------------------------------------------------------------
// GET /calendar-categories (reference)
// ---------------------------------------------------------------------------
function apiCalendarCategoriesList(PDO $conn, array $apiKey, array $params, array $body): void {
    $rows = $conn->query(
        "SELECT c.id, c.name, c.color, c.description, c.is_active,
                (SELECT COUNT(*) FROM calendar_events e WHERE e.category_id = c.id) AS event_count
         FROM calendar_categories c ORDER BY c.name"
    )->fetchAll(PDO::FETCH_ASSOC);
    apiRespond(array_map(function ($c) {
        return [
            'id'          => (int)$c['id'],
            'name'        => $c['name'],
            'color'       => $c['color'],
            'description' => $c['description'],
            'is_active'   => (bool)$c['is_active'],
            'event_count' => (int)$c['event_count'],
        ];
    }, $rows));
}
